# Generated by Django 6.0 on 2025-12-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='buy_price',
        ),
    ]
